spring.application.name=HospitalManagementSystem

#DataBaseConfiguration
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_db
spring.datasource.username=hospitaldb
spring.datasource.password=admin123

#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#SecurityConfiguration
spring.security.user.name=aprexter
spring.security.user.password=password


jwt.secretKey=Q7vK3mN9xR2pL8sW4dF6hJ1cZ5aB0yT8uI3oP6qR9wE2sX7mN4kL8vC1dF5gH0jK
jwt.issuer=aprexter
jwt.expiration-time=3600000


